### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by lepisma** [Vernacular-ai/ml#18]
Hey @AnirudhDagar we posted the bad post also but now realizing that the images are not showing up. Can you check?

**Comment by AnirudhDagar** [comment]
Hi @lepisma I think we need to build and publish using `gatsby build --prefix-paths` for the images to render. Can you please try this on the `gh-pages` branch? I think this was a previous issue as well which was solved by setting the above option, otherwise, the paths are not right after deployment (and work locally only).

**Comment by lepisma** [comment]
I just run `yarn deploy`. The script inside does `--prefix-paths` thing. Let me check again though.

**Comment by lepisma** [comment]
bro check yarn deploy command. it's not working. it sshould right?

**Comment by AnirudhDagar** [comment]
I deployed and published the page twice, and for now, the images are rendering fine, but this seems like a weird issue (maybe intermittent). I did some searching and found multiple issues reporting the same problem as [here](https://github.com/gatsbyjs/gatsby/issues/24814). Not sure what the root cause is.

**Comment by lepisma** [comment]
:( ok closing
